repos:
  - repo: https://github.com/mverteuil/precommit-dephell
    rev: master
    hooks:
      - id: dephell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        exclude: setup.py
        language_version: python3.8
