name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    container:
      image: python

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Setup dependencies
        run: |
          poetry install

      - name: Test with pytest
        run: poetry run pytest
